import type { JournalEntry } from "@/lib/data/fieldwork-types";

export const JOURNAL_ENTRY_TYPES = [
  "observation", "conversation", "interview", "site_visit", "event", "idea", "media",
] as const;

export class JournalCaptureError extends Error {
  constructor(public readonly code: "invalid_input" | "request_conflict" | "unconfirmed", message: string) {
    super(message);
    this.name = "JournalCaptureError";
  }
}

export type JournalCaptureRow = Omit<JournalEntry, "created_at" | "updated_at">;
export interface JournalCaptureStore {
  read(id: string): Promise<JournalEntry | null>;
  insert(row: JournalCaptureRow): Promise<void>;
}

export function validCaptureId(id: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
}

/** Compare submitted fields, not database receipt timestamps or later pin changes.
 * The legacy consent timestamp is generated by the server at receipt; it is not
 * part of the retry identity. The consent follow-up replaces that legacy behavior.
 */
function submittedFields(row: JournalCaptureRow): string {
  return JSON.stringify([
    row.user_id, row.entry_type, row.title, row.content, row.location, row.corridor,
    row.tags, row.contact_ids, row.linked_case_id, row.attachments,
    row.consent_status, row.consent_method, row.consent_jurisdiction,
  ]);
}

/** Append-only capture with a client-held request ID. A lost response can be retried
 * verbatim; an existing different/edited record is never overwritten or upserted.
 * A successful result always includes a database readback. This is not a transaction.
 */
export async function saveJournalCapture(store: JournalCaptureStore, row: JournalCaptureRow) {
  if (!validCaptureId(row.id) || !validCaptureId(row.user_id)) {
    throw new JournalCaptureError("invalid_input", "Invalid journal request identifier.");
  }
  const expected = submittedFields(row);
  async function recover() {
    let found: JournalEntry | null;
    try { found = await store.read(row.id); }
    catch { throw new JournalCaptureError("unconfirmed", "The save could not be checked. Retry the same entry; do not start a duplicate."); }
    if (!found) return null;
    if (found.id !== row.id || submittedFields(found) !== expected) {
      throw new JournalCaptureError("request_conflict", "This entry ID already has different saved content. Nothing was overwritten. Export this proposal before reviewing the saved entry.");
    }
    return found;
  }
  const earlier = await recover();
  if (earlier) return { entry: earlier, replayed: true };
  try { await store.insert(row); }
  catch {
    const recovered = await recover();
    if (recovered) return { entry: recovered, replayed: true };
    throw new JournalCaptureError("unconfirmed", "The save was not confirmed. Your text is still here; retry the same entry or export it.");
  }
  const confirmed = await recover();
  if (!confirmed) throw new JournalCaptureError("unconfirmed", "The saved entry could not be read back. Retry the same entry or export it.");
  return { entry: confirmed, replayed: false };
}
